### ISSUE TITLE
不清晰的lock逻辑，iterator文件未被使用

### ISSUE THREAD

**Issue by Impersonality** [Kirov7/CouloyDB#15]
您好，我最近在阅读代码时，关于数据库的lock逻辑中，有的地方让我困惑。

根据我阅读代码时的理解，db.mu的用途是对磁盘文件读写时加锁，索引的数据结构有单独的mu。

例如，在文件db.go的第112行，db.mu在Get函数中对索引加了锁，而在Put/Delete db.mu没有对索引加锁。
在文件db.go的第182行，db.mu在Fold函数中也对索引加了锁。

还有个问题是，iterator文件未被使用。

我相信您对这个项目有更深入的了解，能够解答我的困惑。我希望这个问题反馈能对您有所帮助，期待您的回复。

感谢您的时间和努力，祝您的项目成功！

**Comment by Kirov7** [comment]
不好意思现在才有空来回答您的问题，你的理解没有问题，db.mu主要是用来在磁盘操作等需要全局锁的时候使用，而memtable中的并发安全控制则是其具体实现来保证，在Get和Fold方法中使用锁的本意是希望读取保证读取磁盘时的并发安全，在这两部分的内部实现中都用到了db.getValueByPos(pos)，但经过你的提醒，我重新审视了这个部分内容，发现两点问题
1. 如果在Get方法要加锁的话中，应该在memtable读取之后再进行加锁操作来细化锁的粒度
2. db.getValueByPos(pos)这个方法可能并不需要并发安全控制，因为磁盘文件一旦写入之后不会再有修改操作，所以对于读取来说是安全的是不会读到脏数据的。所以在这里加锁可能是一个冗余的不必要操作。
所以，这部分应该是需要修改的。
至于iteator.go中的内容是提供给上层使用方进行调用的，使用权交给上层，在CouloyDB的内部实现中没有被使用到。
这个项目可能还有着很多不完善的地方，感谢你的指正，你也可以直接提交pr来进行修改，如有其他的问题与建议，欢迎讨论。

**Comment by Impersonality** [comment]
是的。我们只看fileIO的实现，读数据使用的函数是 f.fd.ReadAt(bytes, offset)，该函数的系统调用是syscall.Pread，没有修改偏移量；bitcaks 写数据是追加写，没有修改，这样看起来是没有并发问题的。

我可以给该问题提交pr么

**Comment by Kirov7** [comment]
可以的，有任何想法都可以直接提交pr并辅以说明，我会感谢你的贡献的

**Comment by Kirov7** [comment]
https://github.com/Kirov7/CouloyDB/issues/19
你可以看一看这个issue，这种情况是否理应被允许也许是个值得思考的问题，欢迎你的讨论
@Impersonality
