### ISSUE TITLE
`

### ISSUE THREAD

**Issue by gaoxiang15125** [Kirov7/CouloyDB#4]
![image](https://user-images.githubusercontent.com/23611483/236718871-83b4f857-e333-4766-b5bd-7ee3366ec2de.png)

**Comment by Kirov7** [comment]
目前 Kuloy 支持使用 redis 的客户端进行连接，我在 README 文档中给出了使用 go-redis 客户端连接 Kuloy 的例子，由于目前并没有实现所有的操作指令，所以有些命令可能会返回 "ERR unknown 'command xxx'" 的错误，目前所支持的操作指令已在 README 文档全部列出。
请问你的问题是？

**Comment by gaoxiang15125** [comment]
没有没啥问题 我想写个java版的redis来着 看了您的项目还以为您写错了

**Comment by Kirov7** [comment]
好的，因为项目中用于集群同步的gossip协议使用了hashicorp/memberlist包，所以在使用Java复刻的时候要寻找其它可用的库来实现该模块，其它部分应该问题不大
issue close
